# Generated by Django 2.2.10 on 2020-04-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
